# 1. Alamat Koneksi ke Database Cloud Online (IP Publik)
db-uri = "postgres://postgres:Ishom210404@103.186.1.69:5432/postgres"

# 2. Schema dan Role Keamanan PostgREST
db-schema = "public"
db-anon-role = "postgres"

# 3. JWT Secret Token (Wajib Disamakan dengan Anon Key di .env Frontend)
jwt-secret = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicG9zdGdyZXMiLCJpc3MiOiJwb3N0Z3Jlc3QifQ.JSzVHZoI2xV_nv93qjaStFvpTOFfjb7vTyPbiYAjDVw"

# 4. Port Jembatan di Laptop Lu
server-port = 3000
server-host = "localhost"
