db-uri = "postgres://postgres:ishom210404@localhost:5432/sovereign_guild_db"
db-schema = "public"
db-anon-role = "postgres"
jwt-secret = "sovereign_guild_local_secret_2024"
server-port = 3000
server-host = "localhost"
